spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskManager_mbf
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: littlefox171103@gmail.com
    password: lnwxizujboahxwrw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  sercurity:
    jwt:
      secret-key: 8e29c681e354368d6ec0358461b9897180c6b9c9e77754cad6cd1c042e306b028e9e214b41e4632576f2e6f0899d4b165f5bb193199702f9c336cfffb0db5d19
      expiration: 86400000 #  1 ngay
      refresh-token:
        expiration: 604800000 #  7 ngay
